In [43]:
import json
import hmac
import hashlib

In [67]:
sha1="8da8e0b7a0400af2f0784bc93eda3b7ae210fd72"
raw_data = b'{"object":"page","entry":[{"id":"113775866993678","time":1590129487458,"messaging":[{"sender":{"id":"2645080842264257"},"recipient":{"id":"113775866993678"},"timestamp":1590129433346,"message":{"mid":"m_Z9hBVhOX06ZUhLeBks1ORT2_Ae7BuGGqTKmWAtcXQHZSlfe-nM0-1ernNaOrbX8_qgEa_tPMT8JPr1vufTq73w","text":"sddsds","nlp":{"entities":{"location":[{"suggested":true,"confidence":0.83491998910904,"value":"sddsds","type":"value"}]},"detected_locales":[{"locale":"en_XX","confidence":0.5154}]}}}]}]}'
APP_SECRET = "d1a3a1dca8951450dfa6abfdd64bca76".encode("utf-8")
# 
result = hmac.new(APP_SECRET, raw_data, hashlib.sha1).hexdigest()
result

'8da8e0b7a0400af2f0784bc93eda3b7ae210fd72'

In [82]:
xx = b'{"object":"page","entry":[{"id":"113775866993678","time":1590115155055,"messaging":[{"sender":{"id":"2645080842264257"},"recipient":{"id":"113775866993678"},"timestamp":1590115111049,"message":{"mid":"m_HtGxRVW9jTtULwNa9bcLGT2_Ae7BuGGqTKmWAtcXQHaxN3IDj8KZDzLtuKhK5Fws8ADu0hdEu2EWoB6PsyME1w","text":"hello","nlp":{"entities":{"sentiment":[{"confidence":0.54351812601089,"value":"positive"}],"greetings":[{"confidence":0.99988770484924,"value":"true"}],"location":[{"suggested":true,"confidence":0.36278835781712,"value":"hello","type":"value"}]},"detected_locales":[{"locale":"en_XX","confidence":0.9236}]}}}]}]}'

raw_data = json.loads(xx.decode('utf-8'))
print(yy)

entry           = raw_data.get('entry')[0] # should loop this
page_id         = entry.get('id')
time            = entry.get('time')
messaging       = entry.get('messaging')[0]
timestamp       = messaging.get("timestamp")
sender          = messaging.get("sender").get("id")
recipient       = messaging.get("recipient").get("id")

message         = messaging.get("message")
text            = message.get("text")
mid             = message.get("mid")

# NLP
nlp             = message.get("nlp").get("entities")
sentiment       = nlp.get("sentiment")[0]
confidence      = sentiment.get("confidence")
sentiment_value = sentiment.get("value")

print(confidence)
print(sentiment_value)
# if yy["object"] ==  "page":
#     print("is page")

{'object': 'page', 'entry': [{'id': '113775866993678', 'time': 1590115155055, 'messaging': [{'sender': {'id': '2645080842264257'}, 'recipient': {'id': '113775866993678'}, 'timestamp': 1590115111049, 'message': {'mid': 'm_HtGxRVW9jTtULwNa9bcLGT2_Ae7BuGGqTKmWAtcXQHaxN3IDj8KZDzLtuKhK5Fws8ADu0hdEu2EWoB6PsyME1w', 'text': 'hello', 'nlp': {'entities': {'sentiment': [{'confidence': 0.54351812601089, 'value': 'positive'}], 'greetings': [{'confidence': 0.99988770484924, 'value': 'true'}], 'location': [{'suggested': True, 'confidence': 0.36278835781712, 'value': 'hello', 'type': 'value'}]}, 'detected_locales': [{'locale': 'en_XX', 'confidence': 0.9236}]}}}]}]}
0.54351812601089
positive


In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:
N , D_in, H, D_out = 64, 1000, 100, 10

In [37]:
x = np.random.randn(N, D_in)
x

array([[-0.03192555, -0.47075233,  1.14649717, ...,  0.57296454,
         0.68930691,  0.93245934],
       [-0.44885159, -1.42202104,  0.95697878, ...,  1.04166148,
         1.05595755, -1.06089794],
       [-0.03227249, -0.42531394, -0.71440261, ...,  0.21897034,
        -0.45908748,  0.29334456],
       ...,
       [ 0.48264605,  0.08174098, -0.28232578, ..., -0.58278537,
        -1.84861988,  0.06010175],
       [ 0.61519278,  0.38886165,  0.0534119 , ...,  0.26012733,
        -1.14304645, -1.17331647],
       [ 0.80413552,  0.34944788, -0.26394144, ...,  1.68615969,
         0.1059165 ,  2.21728332]])

In [38]:
y = np.random.randn(N, D_out)
y

array([[-2.68845091e-01, -7.94207306e-03,  1.27364699e+00,
         1.08903919e+00,  2.78731557e-01,  9.68790252e-01,
        -1.34510221e+00,  3.31489725e-01, -5.26534499e-01,
        -7.11822731e-01],
       [-3.43134489e-01, -2.37917786e-01,  7.01626703e-01,
        -1.38152024e+00,  2.09137538e-01,  4.15926633e-01,
         2.75140163e-01, -6.23942136e-01, -2.24958389e-01,
         9.24641358e-01],
       [ 2.96003369e-01, -8.83890703e-01,  1.18261737e+00,
         1.24568321e+00, -1.16322485e+00,  1.28895487e+00,
         1.63570030e+00,  1.10256108e+00,  7.26328095e-01,
        -4.46516615e-01],
       [-1.44736173e-01, -2.64526240e+00, -4.08812110e-02,
        -4.41220705e-01,  5.88656712e-01,  1.52118756e+00,
        -8.00315597e-01,  1.87174532e+00,  1.12845805e-01,
        -7.93286799e-02],
       [-1.79447356e+00,  1.13345298e+00, -1.18322543e+00,
         2.18047204e-01,  1.96778678e+00,  9.99283219e-01,
         1.58589077e-01,  1.36656627e+00, -3.28821734e-01,
        -8.

In [39]:
# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)
learning_rate = 1e-6

for t in (range(500)):
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)
    
   # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu= grad_y_pred.dot(w2.T)
    
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    
    grad_w1 = x.T.dot(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    

0 32085133.40370199
1 28708780.317978203
2 32877464.90333462
3 38761346.94023684
4 39875668.09032264
5 31554023.750850804
6 18650969.39269156
7 8706262.547176313
8 3892671.526204164
9 1971112.5439450843
10 1222165.1105225584
11 888042.6990141121
12 705970.2714921767
13 586177.622250393
14 497006.49311463104
15 426279.585921184
16 368269.44915420417
17 319910.9450882198
18 279228.00782551896
19 244675.78854847868
20 215152.4632159088
21 189868.67363174137
22 168056.6398998552
23 149154.43321328348
24 132711.22880220218
25 118358.49030155173
26 105790.77942642281
27 94766.93478827793
28 85061.42790593031
29 76495.95223407402
30 68918.84667873685
31 62198.93356460889
32 56214.879597615996
33 50883.66632301122
34 46128.664362769196
35 41884.51820499715
36 38080.252943095096
37 34668.956973486114
38 31602.43046971891
39 28848.06065850546
40 26365.99570386642
41 24123.326486328173
42 22095.055875600818
43 20258.543954825756
44 18594.228925370153
45 17082.655895697917
46 15708.589121950114
47

405 7.529888011232507e-05
406 7.183619355589932e-05
407 6.853643606183101e-05
408 6.538596085057521e-05
409 6.238259836662948e-05
410 5.951735430796091e-05
411 5.678340812817831e-05
412 5.417574369879015e-05
413 5.1688389467047206e-05
414 4.931601757461001e-05
415 4.705331999939871e-05
416 4.4896856295194906e-05
417 4.283797794808117e-05
418 4.0873716546060876e-05
419 3.8999823766955376e-05
420 3.721222177381335e-05
421 3.550693066217001e-05
422 3.3880260434714926e-05
423 3.232837889692949e-05
424 3.0848100255389805e-05
425 2.9437232188902107e-05
426 2.8089752184901362e-05
427 2.6804318251335532e-05
428 2.557839157462571e-05
429 2.440904677199009e-05
430 2.3292912053782053e-05
431 2.2228012701204642e-05
432 2.1212046181443353e-05
433 2.0242746938001136e-05
434 1.931862498523716e-05
435 1.8436090028888645e-05
436 1.759405273351536e-05
437 1.6790616008492463e-05
438 1.6024027821854112e-05
439 1.5292605086730655e-05
440 1.4594810458515711e-05
441 1.392893490456055e-05
442 1.32937108644640

In [48]:
print(np.shape(h_relu.T))
print(np.shape(grad_y_pred))




(100, 64)
(64, 10)


In [11]:
[h<0]

[array([[ True,  True,  True, ...,  True, False, False],
        [ True,  True,  True, ..., False, False,  True],
        [ True, False,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ..., False, False,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]])]

In [33]:
xx = np.random.randn(3,3)
xx

array([[ 2.17173191, -0.02546685,  0.45822743],
       [ 1.08903276,  1.58713349,  1.82634367],
       [ 0.20697421, -0.68208373,  1.85130839]])

In [34]:
xx.T


array([[ 2.17173191,  1.08903276,  0.20697421],
       [-0.02546685,  1.58713349, -0.68208373],
       [ 0.45822743,  1.82634367,  1.85130839]])

In [25]:
negs = [ xx<0 ]
negs

[array([[ True,  True,  True],
        [ True, False,  True],
        [False,  True, False]])]

In [30]:
xx [ negs ] 

<ipython-input-30-90677945c34b>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  xx [ negs ]


array([0., 0., 0., 0., 0., 0.])

In [50]:
grad_w1

array([[-1.40878456e-04,  1.15326936e-03,  1.64448096e-04, ...,
         1.87742360e-04,  1.01035776e-03,  1.59252240e-03],
       [ 2.32555772e-05, -1.22436644e-04,  3.13972335e-04, ...,
         5.40109100e-04,  9.60794860e-05,  5.44340103e-04],
       [-1.61087539e-04, -4.69779801e-04,  1.80031946e-04, ...,
        -3.54012131e-04,  2.38083178e-05,  1.62561036e-05],
       ...,
       [-4.47627479e-04, -1.94694886e-04, -8.72289633e-04, ...,
        -1.54943820e-04, -3.24647912e-04,  1.20997972e-03],
       [ 2.63528007e-04, -1.59079794e-04,  1.43272876e-04, ...,
        -1.78037309e-04,  7.99389514e-04,  9.40775688e-04],
       [ 1.14650634e-04, -2.51904144e-04, -8.58542668e-04, ...,
        -2.94505443e-04,  2.26048576e-04,  1.06052905e-03]])

In [49]:
import torch

ModuleNotFoundError: No module named 'torch'

In [5]:
import json, requests

In [19]:
page_id = "113775866993678"
post = "hello"
PAT = "EAADqbBNa0pIBAPfu1R6dPTe7uVAGJWAN3rmoTHfVOxZAlTQdERS81dPqM3WV7IiHMatiaXmer7tlpM2LJ49ZByw09PcXnGaazs8KHwYNOfUyYKoma5209u00j5wrUH7qpnkZA46HcbaXiho6x8V70SkPRJxWKDTjNOSZCVSZAOQZDZD"
params = (
    ('message', post),
  #  ('link', 'https://portal.facebook.com/products/'),
    ('access_token', PAT),
)

response = requests.post(f"https://graph.facebook.com/{page_id}/feed", params=params)

In [22]:
dir(response)


['__attrs__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_content',
 '_content_consumed',
 '_next',
 'apparent_encoding',
 'close',
 'connection',
 'content',
 'cookies',
 'elapsed',
 'encoding',
 'headers',
 'history',
 'is_permanent_redirect',
 'is_redirect',
 'iter_content',
 'iter_lines',
 'json',
 'links',
 'next',
 'ok',
 'raise_for_status',
 'raw',
 'reason',
 'request',
 'status_code',
 'text',
 'url']

In [25]:
(response.content)
import json

In [54]:
xx = json.dumps( {'data': [{'access_token': 'EAADqbBNa0pIBAPfu1R6dPTe7uVAGJWAN3rmoTHfVOxZAlTQdERS81dPqM3WV7IiHMatiaXmer7tlpM2LJ49ZByw09PcXnGaazs8KHwYNOfUyYKoma5209u00j5wrUH7qpnkZA46HcbaXiho6x8V70SkPRJxWKDTjNOSZCVSZAOQZDZD', 'category': 'Just For Fun', 'category_list': [{'id': '129417183848258', 'name': 'Just For Fun'}], 'name': 'Testpage', 'id': '113775866993678', 'tasks': ['ANALYZE', 'ADVERTISE', 'MODERATE', 'CREATE_CONTENT', 'MANAGE']}], 'paging': {'cursors': {'before': 'MTEzNzc1ODY2OTkzNjc4', 'after': 'MTEzNzc1ODY2OTkzNjc4'}}})
yy = json.loads(xx)
yy["data"]
for x in yy.get('data'):
    ww = x.get('tasks')
    print(ww)
    if 'CREATE_CONTENT' in ww:
        print("got it")
# for range(yy["data"]):
#     yy[page]


['ANALYZE', 'ADVERTISE', 'MODERATE', 'CREATE_CONTENT', 'MANAGE']
got it


In [62]:
params = (
    ('message', "xxx"),
    ('hi', "bye"),

)

params.add(("hi","heeeo"))

AttributeError: 'tuple' object has no attribute 'add'